name: Auto PR and Deploy to ServiceNow QA

on:
  push:
    branches:
      - sn_instances/dev313587
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  create-pr-to-qa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/sn_instances/dev313587'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request to QA (main)
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sn_instances/dev313587
          base: main
          title: "Promote: Dev changes to QA"
          body: |
            This pull request was automatically created to promote changes from `sn_instances/dev313587` to `main` (QA).
          delete-branch: false
          draft: false

  deploy-to-servicenow-qa:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to ServiceNow QA
        run: |
          curl -X POST "https://${{ secrets.SN_INSTANCE }}.service-now.com/api/sn_cicd/app_repo/install" \
            --user "${{ secrets.SN_USERNAME }}:${{ secrets.SN_PASSWORD }}" \
            --header "Content-Type: application/json" \
            --data '{
              "application_scope": "x_1791345_demo_d_0",
              "version": "1.0.0",
              "auto_upgrade_base_app": true
            }'
