name: ServiceNow QA Deployment

on:
  push:
    branches:
      - sn_instances/dev313587
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  create-pr-to-qa:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request from dev to qa
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: sn_instances/dev313587
          branch: main
          title: "Auto PR: Promote dev changes to QA"
          body: "This PR promotes changes from `dev` to `qa` branch."
          delete-branch: false  # We don't want to delete the dev branch

  deploy-to-servicenow-qa:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'qa'
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to ServiceNow QA
        run: |
          curl -X POST "https://${{ secrets.SN_INSTANCE }}.service-now.com/api/sn_cicd/app_repo/install" \
            --user "${{ secrets.SN_USERNAME }}:${{ secrets.SN_PASSWORD }}" \
            --header "Content-Type: application/json" \
            --data '{
              "application_scope": "x_1791345_demo_d_0",
              "version": "1.0.0",
              "auto_upgrade_base_app": true
            }'
